/**
 * Lua language-server stubs (`---@meta`) generated from the API cards, one
 * file per runtime. They give VS Code, Cursor and any LuaLS-based editor
 * completion and hover text for `Open77.*` and the globals, from the same
 * catalogue the MCP answers from.
 *
 * Types are the documented parameter types where the card has one (`string`,
 * `integer`, `number`, `boolean`, `table`, `function`, `entity`, `value`)
 * mapped onto LuaLS names; anything else becomes `any`. Nothing is invented:
 * a card with an inferred signature is emitted with its inferred names.
 */

import type { ApiCard } from "./types.js";

const TYPE_MAP: Record<string, string> = {
  string: "string",
  integer: "integer",
  number: "number",
  boolean: "boolean",
  table: "table",
  function: "function",
  entity: "integer|string",
  value: "any",
  any: "any",
  vector3: "vector3",
  vector: "vector3",
};

function luaType(type: string): string {
  const key = type.trim().toLowerCase().replace(/\?$/, "");
  return TYPE_MAP[key] ?? "any";
}

function luaIdentifier(name: string, index: number): string {
  const cleaned = name.replace(/[^A-Za-z0-9_]/g, "_").replace(/^(\d)/, "_$1");
  const reserved = new Set(["and", "break", "do", "else", "elseif", "end", "false", "for", "function", "goto", "if", "in", "local", "nil", "not", "or", "repeat", "return", "then", "true", "until", "while"]);
  return cleaned && !reserved.has(cleaned) ? cleaned : `arg${index + 1}`;
}

function docLines(text: string): string[] {
  return text
    .replace(/\r\n/g, "\n")
    .split("\n")
    .map((line) => `--- ${line}`.trimEnd());
}

function emitCard(card: ApiCard): string {
  const out: string[] = [];
  out.push(...docLines(card.summary || card.qualified));
  if (card.description) {
    out.push("---");
    out.push(...docLines(card.description));
  }
  const notes: string[] = [];
  if (card.permissions.length) notes.push(`Permissions: ${card.permissions.join(", ")}`);
  if (card.since) notes.push(`Since: ${card.since}`);
  else notes.push("Since: not in any published build");
  if (card.reasons.length) notes.push(`Reasons: ${card.reasons.join(", ")}`);
  if (notes.length) {
    out.push("---");
    for (const note of notes) out.push(`--- ${note}`);
  }
  const params = card.params.map((param, index) => {
    const name = luaIdentifier(param.name, index);
    out.push(`---@param ${name}${param.optional ? "?" : ""} ${luaType(param.type)}`);
    return name;
  });
  for (const ret of card.returns) {
    // `value, or nil, reason` -> the first word as the name, the rest as a comment.
    const words = ret.replace(/[^A-Za-z0-9_ ]/g, " ").trim().split(/\s+/).filter(Boolean);
    const name = words[0] && /^[A-Za-z_]\w*$/.test(words[0]) ? words[0] : "";
    out.push(`---@return any ${name} ${ret}`.replace(/\s+/g, " ").trimEnd());
  }
  const target = card.namespace === "_G" ? card.name : `${card.namespace}.${card.name}`;
  const isMethod = card.namespace.endsWith("Page") || card.namespace === "Open77.Promise" || card.namespace === "Open77.EventVerdict";
  out.push(`function ${isMethod ? target.replace(/\.([^.]+)$/, ":$1") : target}(${params.join(", ")}) end`);
  out.push("");
  return out.join("\n");
}

function emitRuntime(runtime: "client" | "server", cards: ApiCard[]): string {
  const header = [
    "---@meta",
    `-- Open77 ${runtime} Lua API stubs, generated by @open2077/mcp from the API catalogue.`,
    "-- Do not edit: regenerate with `open77-mcp types`.",
    "",
    "---@class vector3",
    "---@field x number",
    "---@field y number",
    "---@field z number",
    "",
  ];
  const body: string[] = [];
  const namespaces = [...new Set(cards.map((c) => c.namespace).filter((n) => n !== "_G"))].sort();
  for (const namespace of namespaces) {
    const parts = namespace.split(".");
    for (let depth = 1; depth <= parts.length; depth += 1) {
      const prefix = parts.slice(0, depth).join(".");
      if (!body.includes(`${prefix} = ${prefix} or {}`)) body.push(`---@class ${prefix}`, `${prefix} = ${prefix} or {}`);
    }
  }
  body.push("");
  const sorted = [...cards].sort((a, b) => (a.namespace + a.name).localeCompare(b.namespace + b.name));
  for (const card of sorted) body.push(emitCard(card));
  return header.concat(body).join("\n");
}

export function generateStubs(cards: ApiCard[]): { client: string; server: string; clientCount: number; serverCount: number } {
  const client = cards.filter((c) => c.runtime === "client");
  const server = cards.filter((c) => c.runtime === "server");
  return {
    client: emitRuntime("client", client),
    server: emitRuntime("server", server),
    clientCount: client.length,
    serverCount: server.length,
  };
}
